[package]
name = "kali"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5.9", features = ["derive"] }
rand = "0.8.5"

[lib]
name = "kali"
path = "src/lib.rs"